; ===============================================================================
;
; DESK TOP v2.0
; For GEOS on the Commodore 64
;
; Reconstructed from binary by Scott Hutter
; ===============================================================================
;
; This File: C64 KERNAL INCLUDES
;
; ===============================================================================

ROM_SECOND  = $FF93
ROM_TKSA    = $FF96
ROM_ACPTR   = $FFA5
ROM_CIOUT   = $FFA8
ROM_UNTLK   = $FFAB
ROM_UNLSN   = $FFAE
ROM_LISTEN  = $FFB1
ROM_TALK    = $FFB4